agents: {}
clients: {}
creator:
  content_context:
  - a fun and engaging slice of life story aimed at an adult audience.
  - a terrifying horror story aimed at an adult audience.
  - a thrilling action story aimed at an adult audience.
  - a mysterious adventure aimed at an adult audience.
  - an epic sci-fi adventure aimed at an adult audience.
game:
  world_state:
    templates:
      state_reinforcement:
        Goals:
          auto_create: false
          description: Long term and short term goals
          favorite: true
          insert: conversation-context
          instructions: Create a long term goal and two short term goals for {character_name}. Your response must only be the long terms and two short term goals.
          interval: 20
          name: Goals
          query: Goals
          state_type: npc

## Long-term memory

#chromadb:
#  embeddings: instructor
#  instructor_device: cuda
#  instructor_model: hkunlp/instructor-xl
  
## Remote LLMs

#openai:
#  api_key: <API_KEY>

#runpod:
#  api_key: <API_KEY>

## TTS (Text-to-Speech)

#elevenlabs:
#  api_key: <API_KEY>

#coqui:
#  api_key: <API_KEY>

#tts:
#  device: cuda
#  model: tts_models/multilingual/multi-dataset/xtts_v2
#  voices:
#  - label: <name>
#    value: <path to .wav for voice sample>